### ISSUE TITLE
Information on mobile base computer and other parts

### ISSUE THREAD

**Issue by xloem** [jimmyyhwu/tidybot#1]
What is needed to replicate the physical assembly of the robot?

**Comment by cedmo8** [comment]
Indeed it would be great to see a bill of materials, but from what I have been able to piece together so far it uses off the shelf Kinova arms and an AGV (Automated guided vehicle) though I don't know which one.

I thought I had found my next project until I found out those parts probably cost $10,000 alone.

I had hoped to find open source & 3D printable options for every part of it but unfortunately that looks not to be the case, at least not yet.

**Comment by xloem** [comment]
Is this information correct?

**Comment by jimmyyhwu** [comment]
The main component that is not included in this release is the mobile base. Those were donated to our lab by Google X and are not commercially available for purchase.

That said, our approach should also work with other mobile manipulator platforms. In our lab, we have been able to completely replicate the TidyBot setup by installing this codebase on new computers.
