### ISSUE TITLE
There seems to be a repository that is not open-source

### ISSUE THREAD

**Issue by taco-wang** [jimmyyhwu/tidybot#4]
git@github.com:stanford-iprl-lab/Mobile_Manipulation_Dev.git ，
in the readme of robot/driver, 
![image](https://github.com/jimmyyhwu/tidybot/assets/16523103/20ed6a2f-fb11-4fed-aef8-e2a500f4574e)
Searched in the github

**Comment by jimmyyhwu** [comment]
Unfortunately the mobile base is not part of this release, see #1.
