### ISSUE TITLE
Simulation?

### ISSUE THREAD

**Issue by AMark-CS** [jimmyyhwu/tidybot#5]
Hello! What a amazing project! But I don't have the robot as you do, however I do want to have a try, so I'm wondering if you could  please offer some ways of simulation, such as Webots or Ubuntu? I'd be grateful!

**Comment by jimmyyhwu** [comment]
We did not use a simulation in this project, so I don't have any relevant code to share, unfortunately. However, our overall system design should still work for a simulated robot, and you can reuse our LLM summarization code since it is not specific to any robot embodiment.

**Comment by AMark-CS** [comment]
> We did not use a simulation in this project, so I don't have any relevant code to share, unfortunately. However, our overall system design should still work for a simulated robot, and you can reuse our LLM summarization code since it is not specific to any robot embodiment.

Thanks!
